Empleados/Empleados/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.departamentos.urls')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Empleados/applications/departamentos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamentos_app'
urlpatterns = [
   path('new_departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),  
   path(
      'departamento-lista/',
      views.DepartamentoListView.as_view(),
      name='departamento_list'),  

]

Empleados/applications/personas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="personas_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'    
    ),
    path(
        'listar-by-area/<shortname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name="empleados_admin"
    ),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
    ),
    path('success/', views.SuccessView.as_view(),name='correcto'),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'),  
]

Empleados/applications/departamentos/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name=models.CharField('Nombre',max_length=50,blank=True,null=True)
    short_name=models.CharField('Nombre corto',max_length=50,unique=True,null=True)
    anulate=models.BooleanField('Anulado',default=False)
    
    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['-name']
        unique_together =('name', 'short_name')
    
    def __str__(self):
        return str(self.id)+'-'+ self.name+'-'+self.short_name
    

Empleados/applications/departamentos/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre= forms.CharField(max_length=50)
    apellidos=forms.CharField(max_length=50)
    departamento=forms.CharField(max_length=50)
    short_name=forms.CharField(max_length=20)

Empleados/applications/departamentos/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic.edit import FormView
from .forms import NewDepartamentoForm
from applications.personas.models import Empleado
from .models import Departamento
from django.views.generic import ListView
# Create your views here.
# vista que no este reform


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamentos/lista.html"
    context_object_name= 'departamentos'

class NewDepartamentoView(FormView):
    template_name='departamentos/new_departamento.html'
    form_class=NewDepartamentoForm
    success_url='/'

    def form_valid(self, form):
        print("******form_vali")

        depa=Departamento(
            name=form.cleaned_data['departamento'],
            short_name=form.cleaned_data['short_name']
        )
        depa.save()

        nombre=form.cleaned_data['nombre']
        apellidos=form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name=nombre,
            last_name=apellidos,
            job="1",
            departamento=depa 
        )
        return super(NewDepartamentoView,self).form_valid(form)

Empleados/templates/departamentos/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <body>
                        {% for  departamento in departamentos  %}
                        <tr>
                            <td>{{departamento.name}}</td>
                            <td>{{departamento.short_name}}</td>
                            <td>
                                <a class="button warning" href="{% url 'personas_app:empleados_area' departamento.short_name %}">Ver Empleados</a>
                            </td>                        
                        </tr>
                        {% endfor %}
                    </body>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    

Empleados/templates/departamentos/new_departamento.html
{% extends 'base.html' %}

{% block title %}
    Registrar departamento
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Registrar departamento</h1>
        <form class="cell callout grid-x grid-margin-x" method="POST"> {% csrf_token %}
            <div class="medium-6 cell">
                <label> Nombres:
                    {{form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Apellidos:
                    {{form.apellidos}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Departamento::
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label> Nombres:
                    {{form.short_name}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button">Guardar</button>
            </div>
        </form>
    </div>
</div>


{% endblock content %}