Empleados/Empleados/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.departamentos.urls')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Empleados/applications/personas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="personas_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'    
    ),
    path(
        'listar-by-area/<shortname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name="empleados_admin"
    ),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
    ),
    path('success/', views.SuccessView.as_view(),name='correcto'),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'),  
]

Empleados/applications/personas/models.py
from django.db import models
from applications.departamentos.models import Departamento
from ckeditor.fields import RichTextField
class Habilidades(models.Model):
    habilidad = models.CharField(("Habilidad"), max_length=50)

    class Meta:
        verbose_name = "Habilidad"
        verbose_name_plural = "Habilidades"

    def __str__(self):
        return str(self.id)+'-'+self.habilidad

class Empleado(models.Model):
    #Mdoelo tabla empleado
    #contador/administrador/otro
    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )
    first_name = models.CharField("Nombres",max_length=60)
    last_name = models.CharField("Apellidos",max_length=60)
    full_name=models.CharField(
        "Nombres completos",
        max_length=120,
        blank=True
    )
    job= models.CharField("Trabajo",max_length=50,choices=JOB_CHOICES)
    departamento=models.ForeignKey(Departamento,on_delete=models.CASCADE)
    avatar=models.ImageField(upload_to='empleado',blank=True,null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField(null=True,blank=True)
    class Meta:
        verbose_name = "Mi Empleado"
        verbose_name_plural ="Empleados de la empresa"
        ordering = ("-first_name",'last_name')
        unique_together = ('first_name', 'departamento')
    
    def __str__(self):
        return str(self.id)+'-'+self.first_name+'-'+self.last_name

Empleados/applications/personas/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model=Empleado
        fields=(
            'first_name', 
            'last_name',
            'job',
            'departamento',
            'avatar',
            'habilidades',
        )
        widgets={
            'habilidades':forms.CheckboxSelectMultiple(),

        }
    

Empleados/applications/personas/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from .forms import EmpleadoForm
from django.urls import reverse_lazy
# Create your views here.
from .models import Empleado

class InicioView(TemplateView):
    template_name = 'inicio.html'

class ListAllEmpleados(ListView):
    template_name = "personas/list_all.html"
    paginate_by = 4
    ordering='first_name'
    context_object_name='empleados'
    def get_queryset(self):
        palabra_clave=self.request.GET.get("kword",'')
        #icontains= busca buscar valores en cadena
        lista=Empleado.objects.filter(
            full_name__icontains=palabra_clave
        )
        return lista

class ListaEmpleadosAdmin(ListView):
    template_name = "personas/lista_empleados.html"
    paginate_by = 10
    ordering='first_name'
    context_object_name='empleados'
    model = Empleado

class ListByAreaEmpleado(ListView):
    """ListByAreaEmple"""
    template_name = "personas/list_by_area.html"
    context_object_name='empleados'
    def get_queryset(self):
        area=self.kwargs['shortname']
        lista=Empleado.objects.filter(
            departamento__short_name=area
        )
        return lista
class ListEmpleadoByKword(ListView):
    """ListByPalabraCLave"""
    template_name = "personas/list_by_kword.html"
    context_object_name = "empleados"
    def get_queryset(self):
        print ("*************")
        palabra_clave=self.request.GET.get("kword",'')
        print("*************",palabra_clave)
        lista=Empleado.objects.filter(
            first_name=palabra_clave
        )
        return lista
    
class ListHabilidadesEmpleado(ListView):
    template_name = "personas/habilidades.html" 
    context_object_name="habilidades"

    def get_queryset(self):
        empleado=Empleado.objects.get(id=1)
        print(empleado.habilidades.all())
        return empleado.habilidades.all()

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "personas/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context=super(EmpleadoDetailView, self).get_context_data(**kwargs)
        context['titulo'] = 'Empleado del mes'
        return context


class SuccessView(TemplateView):
    template_name = "personas/success.html"

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "personas/add.html"
    form_class=EmpleadoForm

    
    success_url= reverse_lazy('personas_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save()
        empleado.full_name=empleado.first_name + " " + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
    
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "personas/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]       
    success_url= reverse_lazy('personas_app:empleados_admin')
    
    def post(self, request, *args, **kwargs):
        self.object=self.get_object()
        print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        return super(EmpleadoUpdateView, self).form_valid(form)

class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "personas/delete.html"
    success_url= reverse_lazy('personas_app:empleados_admin')
   

Empleados/templates/personas/add.html
{% extends 'base.html' %}

{% block title %}
    Registrar empleado 
{% endblock title %}

{% block content %}
{% load static %}
{% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar personas</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres:
                    {{form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos:
                    {{form.last_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Trabajo:
                    {{form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento:
                    {{form.departamento}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Habilidades:
                    {{form.habilidades}}
                </label>
            </div>
            <div class="medium-12 cell">
                <label>Avatar:
                    {{form.avatar}}
                </label>
            </div>
            <div class="medium-12 cell">
                <button type="submit" class="button success">Guardar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

Empleados/templates/personas/delete.html
{% extends 'base.html' %}

{% block title %}
    Eliminar empleado
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Eliminar empleado: {{object.full_name}}</h1>
        <form  class ="cell" method="POST"> {% csrf_token %}
            <div class="callout secondary">
                <h5>¿Desea eliminar este empleado?</h5>
                <button type="submit" class="alert button">Eliminar</button>
            </div> 
        </form>
    </div>
</div>
{% endblock content %}

Empleados/templates/personas/detail_empleado.html
{% extends 'base.html' %}

{% load static %}
{% block title %}
    Empleado: {{object.full_name}}
{% endblock title %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div clas="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px; margin-top:10px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>

            {% if empleado.avatar  %}
                <img src="{{empleado.avatar.url}}">
            {% else %}
                <img src="{% static 'img/images.png' %}">
            {% endif %}

            <div class="card-section">
                <h4>{{empleado.full_name}}</h4>
                <p>{{empleado.first_name}}</p>
                <p>{{empleado.last_name}}</p>
                <p>{{empleado.departamento.short_name}}</p>
                <p><span class="label"> Habilidades:</span></p>
                <ul class="vertical menu">
                    
                    {% for h in empleado.habilidades.all %}
                        <li>{{h.habilidad}}</li>
                    {% endfor %}
                        
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

Empleados/templates/personas/habilidades.html
<h1>Habilidades de empleados</h1>
<ul>
    {% for h in habilidades  %}
        <li>{{h}}</li>
    {% endfor %}       
</ul>

Empleados/templates/personas/list_all.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Lista empleados</h1>
    <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
      <div class="cell large-7">
          <input type="text" id="kword" name="kword" placeholder="Buscar empleado">
      </div>
      <div class="cell large-2">
          <button type="submit" class="success button">Guardar</button>
      </div>
    </form>   
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>NOMBRES</th>
            <th width="150">APELLIDOS</th>
            <th width="150">DEPARTAMENTOS</th>
            <th width="150">ACCION</th>
          </tr>
        </thead>
        <tbody>
          {% for e in empleados %}
          <tr>
            <td>{{e.id}}</td>
            <td>{{e.first_name}}</td>
            <td>{{e.last_name}}</td>
            <td>{{e.departamento}}</td>
            <td><a class="button warning" href="{% url 'personas_app:empleado_detail' e.id %}">Ver</a></td>
          </tr>
          {% endfor %} 
        </tbody>
      </table>
    </div>
    <div>
      {% if is_paginated  %}
        <nav aria-label="Pagination">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="pagination-previous">
              <a href ="?page={{page_obj.previous_page_number}}">Atras</a>
            </li>
            {% endif %}  
              
            {% for pagina in paginator.page_range %}
            {% if pagina == page_obj.number %} 
            <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
            {% else %}
            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li class="pagination-next">
              <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
            </li>
            {% endif %} 
          </ul>
        </nav> 
      {% endif %}
    </div>
  </div>        
</div>
{% endblock content %}

Empleados/templates/personas/list_by_area.html
{% extends 'base.html' %}


{% block title %}
    lista de empleados por departamento
{% endblock title %}


{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">Empleados por area</div>
            <div class="cell">
                <table>
                    <thead>
                      <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTOS</th>
                        <th width="150">ACCION</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for e in empleados %}
                      <tr>
                        <td>{{e.id}}</td>
                        <td>{{e.first_name}}</td>
                        <td>{{e.last_name}}</td>
                        <td>{{e.departamento}}</td>
                        <td><a class="button warning" href="{% url 'personas_app:empleado_detail' e.id %}">Ver</a></td>
                      </tr>
                      {% endfor %} 
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
    
<h1>Listar por departamento</h1>

<ul>
    
    {% for e in object_list %}
        {{e}}
    {% endfor %}
        
</ul>

Empleados/templates/personas/list_by_kword.html
<h1>Buscar Empleados</h1>
<form method="GET"> {% csrf_token %}
    <input type="text" id="kword" name = "kword" placeholder="Ingrese nombre aqui">
    <button type="submit">Buscar</button>
</form>

<h3>Lista Resultados:</h3>
<ul>
    {% for e in empleados %}
        <li>{{e}}</li>
    {% endfor %}    
</ul>

Empleados/templates/personas/lista_empleados.html
{% extends 'base.html' %}

{% block content %}
{% include "includes/header.html" %}
<div class="grid-container">
  <div class="grid-x">
    <h1 class="cell">Lista empleados</h1>  
    <div class="cell">
      <table>
        <thead>
          <tr>
            <th width="200">ID</th>
            <th>NOMBRES</th>
            <th width="150">APELLIDOS</th>
            <th width="150">DEPARTAMENTOS</th>
            <th width="150">ACCION</th>
          </tr>
        </thead>
        <tbody>
          {% for e in empleados %}
          <tr>
            <td>{{e.id}}</td>
            <td>{{e.first_name}}</td>
            <td>{{e.last_name}}</td>
            <td>{{e.departamento}}</td>
            <td>
                <a class="button success" href="{% url 'personas_app:modificar_empleado' e.id %}">Editar</a>
            </td>
            <td>
                <a class="button alert" href="{% url 'personas_app:eliminar_empleado' e.id %}">Eliminar</a>
            </td>
          </tr>
          {% endfor %} 
        </tbody>
      </table>
    </div>
    <div>
      {% if is_paginated  %}
        <nav aria-label="Pagination">
          <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="pagination-previous">
              <a href ="?page={{page_obj.previous_page_number}}">Atras</a>
            </li>
            {% endif %}  
              
            {% for pagina in paginator.page_range %}
            {% if pagina == page_obj.number %} 
            <li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
            {% else %}
            <li><a href="?page={{pagina}}">{{pagina}}</a></li>
            {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
            <li class="pagination-next">
              <a href="?page={{page_obj.next_page_number}}">Siguiente</a>
            </li>
            {% endif %} 
          </ul>
        </nav> 
      {% endif %}
    </div>
  </div>        
</div>
{% endblock content %}

Empleados/templates/personas/success.html
<h1>FELICITACIONES SE GUARDO CORRECTAMENTE</h1>

Empleados/templates/personas/update.html
{% extends 'base.html' %}
{% block title  %}
    Editar Empleado
{% endblock title  %}

{% block content %}

{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Modificar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="cell large-6">
                    <label>Nombres:
                        {{form.first_name}}
                    </label>
                </div>    
                <div class="cell large-6">
                    <label>Apellidos:
                        {{form.last_name}}
                    </label>
                </div>  
                <div class="cell large-6">
                    <label>Trabajo:
                        {{form.job}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Area:
                        {{form.departamento}}
                    </label>
                </div>
                <div class="cell large-6">
                    <label>Habilidades extra:
                        {{form.habilidades}}
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="submit success button">Guardar</button>
                </div>                        
            </form>
        </div>
    </div>
</div>

{% endblock content %}