Empleados/Empleados/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.departamentos.urls')),
] + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Empleados/applications/departamentos/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'departamentos_app'
urlpatterns = [
   path('new_departamento/', views.NewDepartamentoView.as_view(),name='nuevo_departamento'),  
   path(
      'departamento-lista/',
      views.DepartamentoListView.as_view(),
      name='departamento_list'),  

]

Empleados/applications/personas/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="personas_app"

urlpatterns = [
    path(
        '', 
        views.InicioView.as_view(),
        name='inicio'
    ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'    
    ),
    path(
        'listar-by-area/<shortname>', 
        views.ListByAreaEmpleado.as_view(),
        name="empleados_area"
    ),
    path(
        'lista-empleados-admin/', 
        views.ListaEmpleadosAdmin.as_view(),
        name="empleados_admin"
    ),
    path('buscar-empleado/', views.ListEmpleadoByKword.as_view()),
    path('habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
    ),
    path(
        'add-empleado/', 
         views.EmpleadoCreateView.as_view(),
         name='empleado_add'
    ),
    path('success/', views.SuccessView.as_view(),name='correcto'),
    path(
        'update-empleado/<pk>', 
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'),
    path(
        'delete-empleado/<pk>', 
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'),  
]

Empleados/templates/includes/header.html
{% load static %}
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li>
        <img class="logo-inmobiliaria" src="{% static 'img/equipo.png' %}">
        </li>
        <li class="menu-text" href="#"> Gestion de empleados </li>
        <li>
          <a href="{% url 'personas_app:empleados_all' %}">Listar</a>
        </li>
        <li><a href="{% url 'departamentos_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'personas_app:empleados_admin' %}">Administrar</a></li>
        <li><a href="{% url 'departamentos_app:nuevo_departamento' %}">Nuevo Departamento</a></li> 
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="{% url 'personas_app:empleado_add' %}" class="button">Nuevo Empleado</a></li>
      </ul>
    </div>
  </div>